name = "macro-classroom"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "8b625fa0635e551b1e10b8051e63d571"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "d1ad4b4cff9344269c76bd8fe78b202b"

[[rules]]
type = "Text"
globs = ["**/*.html"]
